export const BESTSELLERS = [
  {
    Section: "scrub",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#FFFAB0", name: "vanilla", dark: true },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub01.jpg?alt=media&token=de2373a9-735b-4f3c-848e-830dd17b303e",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub02.jpg?alt=media&token=ccf3309b-c6f7-44c5-8f37-9206c7e42eac",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub03.jpg?alt=media&token=1785a8d4-82ab-452d-bb4d-d6405523af43",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub10.jpg?alt=media&token=ba961678-1058-4286-b36b-663787823f18",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub11.jpg?alt=media&token=f472927d-8fb5-40c7-95ef-d3c7b5d38f64",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub12.jpg?alt=media&token=81a9b217-9aa6-4115-b80f-68bc02f3ccb3",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub13.jpg?alt=media&token=4535a4c9-d0cd-4db2-8495-ba123e31f94c",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
  {
    Section: "scrub",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AE6F35", name: "sand", dark: false },
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 35,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub18.jpg?alt=media&token=3f85e95f-7f62-4420-b973-b274eb30b154",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub11.jpg?alt=media&token=f472927d-8fb5-40c7-95ef-d3c7b5d38f64",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub05.jpg?alt=media&token=1bd9d2c3-84f5-495d-9eca-bc975bca7c9f",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub14.jpg?alt=media&token=177baf85-6e97-4b64-935c-0706a835c92f",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub15.jpg?alt=media&token=395a5a78-31ed-4011-beeb-54507de74cf5",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub16.jpg?alt=media&token=df475800-c2c8-42b5-a042-4cc2724cf503",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub17.jpg?alt=media&token=3ae0cebb-1112-4342-831d-da3900446c07",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
  {
    Section: "scrub",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#DA9A6A", name: "terracota", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 0 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 50,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 20,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub24.jpg?alt=media&token=24259631-bf99-493b-96d3-8ffaf576f482",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub25.jpg?alt=media&token=8491d980-2557-4be6-818b-24919a290089",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub07.jpg?alt=media&token=40e6e53e-df68-4bea-8fdf-4dee7a33e2d8",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub18.jpg?alt=media&token=3f85e95f-7f62-4420-b973-b274eb30b154",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub19.jpg?alt=media&token=44d18919-8991-41de-aa70-8fc274fdd0ae",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub20.jpg?alt=media&token=d5687713-9665-490a-98a0-5d43e4d34568",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub21.jpg?alt=media&token=101b9473-2544-4b13-babd-d52fbe54d722",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
  {
    Section: "scrub",
    Reference: "REFSCW20003WH",
    Name: "BERTA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#C44779", name: "pink", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 60,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 40,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub06.jpg?alt=media&token=22788dcf-4d94-4e4c-a983-2c65954918b9",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub03.jpg?alt=media&token=1785a8d4-82ab-452d-bb4d-d6405523af43",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub04.jpg?alt=media&token=4e9387be-8b13-4f26-8fc7-d14cd753e255",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub22.jpg?alt=media&token=4996980a-71df-4258-8aa8-d1de811517e0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub23.jpg?alt=media&token=09ae579d-3638-4fc3-844b-68c1fb6606e8",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub24.jpg?alt=media&token=24259631-bf99-493b-96d3-8ffaf576f482",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub25.jpg?alt=media&token=8491d980-2557-4be6-818b-24919a290089",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
  {
    Section: "scrub",
    Reference: "REFSCW20001ST",
    Name: "SARAH",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AD9D6B", name: "ochre", dark: false },
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 55,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub08.jpg?alt=media&token=8899f7de-c4d8-4f02-85a4-3fe17b815f10",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub09.jpg?alt=media&token=5d5f0b38-e63c-44fb-8be9-c45b7b50aad0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub05.jpg?alt=media&token=1bd9d2c3-84f5-495d-9eca-bc975bca7c9f",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub22.jpg?alt=media&token=4996980a-71df-4258-8aa8-d1de811517e0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub23.jpg?alt=media&token=09ae579d-3638-4fc3-844b-68c1fb6606e8",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub20.jpg?alt=media&token=d5687713-9665-490a-98a0-5d43e4d34568",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub21.jpg?alt=media&token=101b9473-2544-4b13-babd-d52fbe54d722",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
  {
    Section: "scrub",
    Reference: "REFSCW20003RE",
    Name: "CLAUDIA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#3D6795", name: "blue", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xxs", units: 0 },
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 0 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Tall",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub09.jpg?alt=media&token=5d5f0b38-e63c-44fb-8be9-c45b7b50aad0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub08.jpg?alt=media&token=8899f7de-c4d8-4f02-85a4-3fe17b815f10",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub01.jpg?alt=media&token=de2373a9-735b-4f3c-848e-830dd17b303e",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub16.jpg?alt=media&token=df475800-c2c8-42b5-a042-4cc2724cf503",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub17.jpg?alt=media&token=3ae0cebb-1112-4342-831d-da3900446c07",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub12.jpg?alt=media&token=81a9b217-9aa6-4115-b80f-68bc02f3ccb3",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub13.jpg?alt=media&token=4535a4c9-d0cd-4db2-8495-ba123e31f94c",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
    Wishlist: false,
  },
];
