export const FACE_MASKS = [
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#FFFFF6", name: "white", dark: true },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 15,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask02.jpg?alt=media&token=f496f6d7-28ab-475d-af6b-a5f3138ae051",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20001MG",
    Name: "BERTA",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#8C8B93", name: "grey", dark: true },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 17,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask01.jpg?alt=media&token=6c6dcf9e-54a5-4ed4-b62e-d71142043a16",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20003RJ",
    Name: "LEO",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#5BA9C2", name: "blue", dark: false },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 17,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask03.jpg?alt=media&token=3fa49735-9138-48b3-9906-c2a85f17fab4",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20004NS",
    Name: "ALBA",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#FFFDF6", name: "white", dark: true },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 19,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask04.jpg?alt=media&token=d85a9b5f-62cd-423a-b8af-e9b8670b51d6",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20004WS",
    Name: "PABLO",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#1D1E22", name: "black", dark: false },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 19,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask06.jpg?alt=media&token=4be870cb-8832-415e-8a8a-a347e3f02953",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "unisex",
    Section: "face-masks",
    Reference: "REFSCW20001MM",
    Name: "LOUIS",
    Description: "Basic Face Mask + pouch",
    Color: { code: "#FFFFF6", name: "white", dark: true },
    Season: "SS20",
    Sizes: [],
    Fit: "Regular",
    Details: "Comfy mask made with soft organic cotton",
    Fabric: [{ material: "Cotton", percent: 100 }],
    Care: ["No dry", "Iron"],
    Price: 21,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: true,
    Sale: true,
    Discount: 10,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Unisex%2FFace-Masks%2Fu_face-mask05.jpg?alt=media&token=d6bb2dbb-5303-486e-a4e8-34fba0c2ca84",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
];
