export const SCRUBS = [
  {
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: "#485E70",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-1.webp",
  },
  {
    Reference: "REFSCW20001SA",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: "#AD9D6B",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-2.webp",
  },
  {
    Reference: "REFSCW20001RE",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: "#AD7F6B",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-3.webp",
  },
];
