export const SCRUB_PANTS = [
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Relaxed Two-Pocket Pants",
    Color: { code: "#46B2B2", name: "green apple", dark: false },
    Season: "SS20",
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 0 },
      { size: "l", units: 0 },
      { size: "xl", units: 0 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 50,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: true,
    Sale: true,
    Discount: 30,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants01.jpg?alt=media&token=378480c2-cdb1-49d2-8809-6333054a43eb",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants02.jpg?alt=media&token=fdd077ec-a444-49c1-b5a5-ac7bb43ba776",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants03.jpg?alt=media&token=19caa36c-cc46-44cc-bacc-76a672e5efc3",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants04.jpg?alt=media&token=c6db5c8a-b73f-41e7-9996-416647f50202",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants05.jpg?alt=media&token=a5ab1d3d-1a71-421b-8dd2-37971edcee02",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants02.jpg?alt=media&token=fdd077ec-a444-49c1-b5a5-ac7bb43ba776",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants03.jpg?alt=media&token=19caa36c-cc46-44cc-bacc-76a672e5efc3",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20003WH",
    Name: "BERTA",
    Description: "Three-Pocket Notched Pants",
    Color: { code: "#A685DE", name: "purple", dark: false },
    Season: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 35,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants11.jpg?alt=media&token=87beff67-6512-4f4b-abe9-739fc7219742",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants12.jpg?alt=media&token=df3199c3-468f-4f71-b102-2acc8bca6b1a",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants13.jpg?alt=media&token=f994eb73-5f1d-40a3-ba91-959ef85e259b",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants14.jpg?alt=media&token=bdcf13d5-daf2-48fc-9f74-c19928c6c232",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants15.jpg?alt=media&token=fb108b0b-df14-42a0-b1f1-293350b2f1ba",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants12.jpg?alt=media&token=df3199c3-468f-4f71-b102-2acc8bca6b1a",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants13.jpg?alt=media&token=f994eb73-5f1d-40a3-ba91-959ef85e259b",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Relaxed Two-Pocket Pants",
    Color: { code: "#84A6DC", name: "pastel blue", dark: true },
    Season: "SS20",
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 0 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 60,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 20,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants21.jpg?alt=media&token=c43343ce-9216-40be-8bd7-9863a033dded",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants22.jpg?alt=media&token=23c7650c-5142-446c-bd43-b67682f452e4",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants23.jpg?alt=media&token=58060054-8f14-43f9-b509-678b4219d107",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants24.jpg?alt=media&token=2119645e-fbf5-46fc-ada4-72876290c5c3",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants25.jpg?alt=media&token=5d7bb958-3ee4-48f9-833f-a114fe2d2b78",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants22.jpg?alt=media&token=23c7650c-5142-446c-bd43-b67682f452e4",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants23.jpg?alt=media&token=58060054-8f14-43f9-b509-678b4219d107",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20003WH",
    Name: "BERTA",
    Description: "Three-Pocket Notched Pants",
    Color: { code: "#57026F", name: "burdeos", dark: false },
    Season: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 60,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 40,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants06.jpg?alt=media&token=b3b73940-7685-4190-a000-07629d28d938",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants07.jpg?alt=media&token=d8f01ab0-4075-41b9-8d07-8878152abeb2",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants08.jpg?alt=media&token=cd0db6d7-302b-4a66-a09c-4b7aae3387dd",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants09.jpg?alt=media&token=f65f7c97-e95a-48d8-8a3f-ad13ecd094e1",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants10.jpg?alt=media&token=85073a8a-5a8e-42ea-948b-53f091fdb9b5",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants07.jpg?alt=media&token=d8f01ab0-4075-41b9-8d07-8878152abeb2",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants08.jpg?alt=media&token=cd0db6d7-302b-4a66-a09c-4b7aae3387dd",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20001ST",
    Name: "SARAH",
    Description: "Two-Pocket Slide-Rib Pants",
    Color: { code: "#585B63", name: "grey", dark: false },
    Season: "SS20",
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 55,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants26.jpg?alt=media&token=c214f380-94b1-46cc-bc24-933fef8529fc",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants27.jpg?alt=media&token=0e5864cd-06a1-4558-aea7-8fdc73cec106",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants28.jpg?alt=media&token=31f5a7fd-1389-4bfe-80d2-dec160242699",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants29.jpg?alt=media&token=c8bc1d2b-0882-4634-89d1-773c70caf081",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants30.jpg?alt=media&token=e39aceac-26c5-4c51-b1e5-825554ff0882",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants27.jpg?alt=media&token=0e5864cd-06a1-4558-aea7-8fdc73cec106",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants28.jpg?alt=media&token=31f5a7fd-1389-4bfe-80d2-dec160242699",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
  {
    Collection: "women",
    Section: "scrub-pants",
    Reference: "REFSCW20003RE",
    Name: "CLAUDIA",
    Description: "Three-Pocket Mock Wrap Pants",
    Color: { code: "#142D76", name: "blue electric", dark: false },
    Season: "SS20",
    Sizes: [
      { size: "xxs", units: 0 },
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 0 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Tall",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: true,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants16.jpg?alt=media&token=1d6ed8f5-2281-4f2b-84c4-a2842014e7a7",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants17.jpg?alt=media&token=fcd6cfc3-c8ea-490b-9180-a3ea586e3965",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants18.jpg?alt=media&token=05da0b22-19fd-4fcf-adfd-a142455d86c3",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants19.jpg?alt=media&token=6d22700e-408f-4e36-81fd-c4f55e34d410",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants20.jpg?alt=media&token=09d140d0-2b9c-48b7-aa3d-dd4e55ccb74b",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants17.jpg?alt=media&token=fcd6cfc3-c8ea-490b-9180-a3ea586e3965",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FPants%2Fwomen_pants18.jpg?alt=media&token=05da0b22-19fd-4fcf-adfd-a142455d86c3",
    ],
    Reviews: [{ user: "", createdAt: "", text: "", qualification: 0 }],
  },
];
