export const SCRUBS = [
  {
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#FFFAB0", name: "vanilla", dark: true },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-1.webp",
  },
  {
    Reference: "REFSCW20001SA",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AE6F35", name: "sand", dark: false },
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-2.webp",
  },
  {
    Reference: "REFSCW20001RE",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#DA9A6A", name: "terracota", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-3.webp",
  },
  {
    Reference: "REFSCW20003WH",
    Name: "BERTA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#C44779", name: "pink", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-1.webp",
  },
  {
    Reference: "REFSCW20001ST",
    Name: "SARAH",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AD9D6B", name: "ochre", dark: false },
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-2.webp",
  },
  {
    Reference: "REFSCW20003RE",
    Name: "CLAUDIA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#3D6795", name: "blue", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xxs", units: 100 },
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Tall",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 20,
    Url: "gs://liblab-web.appspot.com/Women/Scrubs/Scrubs-Suit-3.webp",
  },
];
