export const SCRUBS = [
  {
    Reference: "REFSCW20001BG",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#FFFAB0", name: "vanilla", dark: true },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub01.jpg?alt=media&token=de2373a9-735b-4f3c-848e-830dd17b303e",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub02.jpg?alt=media&token=ccf3309b-c6f7-44c5-8f37-9206c7e42eac",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub03.jpg?alt=media&token=1785a8d4-82ab-452d-bb4d-d6405523af43",
    ],
  },
  {
    Reference: "REFSCW20001SA",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AE6F35", name: "sand", dark: false },
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 35,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub02.jpg?alt=media&token=ccf3309b-c6f7-44c5-8f37-9206c7e42eac",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub04.jpg?alt=media&token=4e9387be-8b13-4f26-8fc7-d14cd753e255",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub05.jpg?alt=media&token=1bd9d2c3-84f5-495d-9eca-bc975bca7c9f",
    ],
  },
  {
    Reference: "REFSCW20001RE",
    Name: "DIANA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#DA9A6A", name: "terracota", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 100 },
      { size: "xl", units: 0 },
    ],
    Fit: "Regular",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 50,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 20,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub05.jpg?alt=media&token=1bd9d2c3-84f5-495d-9eca-bc975bca7c9f",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub06.jpg?alt=media&token=22788dcf-4d94-4e4c-a983-2c65954918b9",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub07.jpg?alt=media&token=40e6e53e-df68-4bea-8fdf-4dee7a33e2d8",
    ],
  },
  {
    Reference: "REFSCW20003WH",
    Name: "BERTA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#C44779", name: "pink", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 60,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: true,
    Discount: 40,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub06.jpg?alt=media&token=22788dcf-4d94-4e4c-a983-2c65954918b9",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub03.jpg?alt=media&token=1785a8d4-82ab-452d-bb4d-d6405523af43",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub04.jpg?alt=media&token=4e9387be-8b13-4f26-8fc7-d14cd753e255",
    ],
  },
  {
    Reference: "REFSCW20001ST",
    Name: "SARAH",
    Description: "Three-Pocket Scrub",
    Color: { code: "#AD9D6B", name: "ochre", dark: false },
    Sizes: [
      { size: "xs", units: 0 },
      { size: "s", units: 0 },
      { size: "m", units: 100 },
      { size: "l", units: 0 },
      { size: "xl", units: 100 },
      { size: "xxl", units: 100 },
    ],
    Fit: "Petite",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 55,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: false,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub08.jpg?alt=media&token=8899f7de-c4d8-4f02-85a4-3fe17b815f10",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub09.jpg?alt=media&token=5d5f0b38-e63c-44fb-8be9-c45b7b50aad0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub05.jpg?alt=media&token=1bd9d2c3-84f5-495d-9eca-bc975bca7c9f",
    ],
  },
  {
    Reference: "REFSCW20003RE",
    Name: "CLAUDIA",
    Description: "Three-Pocket Scrub",
    Color: { code: "#3D6795", name: "blue", dark: false },
    Collection: "SS20",
    Sizes: [
      { size: "xxs", units: 0 },
      { size: "xs", units: 100 },
      { size: "s", units: 100 },
      { size: "m", units: 0 },
      { size: "l", units: 100 },
      { size: "xl", units: 100 },
    ],
    Fit: "Tall",
    Details:
      "When one pocket just isn't enough. With a modern V-neck, tailored fit and three pockets, the DIANA fulfills all your stashing needs",
    Fabric: [
      { material: "Polyester", percent: 71 },
      { material: "Rayon", percent: 21 },
      { material: "Spandex", percent: 7 },
    ],
    Care: ["No dry", "Iron"],
    Price: 45,
    Reviews: [{ user: "", date: "", rating: 0, comment: "" }],
    New: true,
    BestSeller: false,
    Sale: false,
    Discount: 0,
    Url: [
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub09.jpg?alt=media&token=5d5f0b38-e63c-44fb-8be9-c45b7b50aad0",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub08.jpg?alt=media&token=8899f7de-c4d8-4f02-85a4-3fe17b815f10",
      "https://firebasestorage.googleapis.com/v0/b/liblab-web.appspot.com/o/Women%2FScrubs%2Fwomen_scrub01.jpg?alt=media&token=de2373a9-735b-4f3c-848e-830dd17b303e",
    ],
  },
];
