export const cartActionTypes = {
  TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  SELECT_SIZE: "SELECT_SIZE",
  CLEAR_SIZE: "CLEAR_SIZE",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  ORDER_ITEMS_START: "ORDER_ITEMS_START",
  ORDER_ITEMS_SUCCESS: "ORDER_ITEMS_SUCCESS",
  ORDER_ITEMS_FAILURE: "ORDER_ITEMS_FAILURE",
};
