const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  DISPLAY_CART: "DISPLAY_CART",
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_FROM_DROPUP_OR_CART: "ADD_ITEM_FROM_DROPUP_OR_CART",
  ADD_ITEM_FROM_WISHLIST: "ADD_ITEM_FROM_WISHLIST",
  SELECT_SIZE: "SELECT_SIZE",
  CLEAR_SIZE: "CLEAR_SIZE",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",
};

export default cartActionTypes;
