const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  SELECT_SIZE: "SELECT_SIZE",
  CLEAR_SIZE: "CLEAR_SIZE",
  REMOVE_ITEM: "REMOVE_ITEM",
  // CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",
};

export default cartActionTypes;
