const collectionsActionTypes = {
  FETCH_COLLECTION_BY_CONDITION_START: "FETCH_COLLECTION_BY_CONDITION_START",
  FETCH_COLLECTION_BY_CONDITION_SUCCESS:
    "FETCH_COLLECTION_BY_CONDITION_SUCCESS",
  FETCH_COLLECTION_BY_CONDITION_FAILURE:
    "FETCH_COLLECTION_BY_CONDITION_FAILURE",
  FETCH_SECTION_START: "FETCH_SECTION_START",
  FETCH_SECTION_SUCCESS: "FETCH_SECTION_SUCCESS",
  FETCH_SECTION_FAILURE: "FETCH_SECTION_FAILURE",
  ORDER_SECTION_PRICE_ASCENDING: "ORDER_SECTION_PRICE_ASCENDING",
  ORDER_SECTION_PRICE_DESCENDING: "ORDER_SECTION_PRICE_DESCENDING",
  RESET_ORDER_SECTION: "RESET_ORDER_SECTION",
  FILTER_COLORS: "FILTER_COLORS",
  FILTER_SIZES: "FILTER_SIZES",
  FILTER_FIT: "FILTER_FIT",
  RESET_GRID_VIEW: "RESET_GRID_VIEW",
  SET_GRID_VIEW: "SET_GRID_VIEW",
  SELECT_ITEM: "SELECT_ITEM",
  TOGGLE_SECTION_WISHLIST: "TOGGLE_SECTION_WISHLIST",
};

export default collectionsActionTypes;
