const collectionsActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  ORDER_COLLECTIONS_PRICE_ASCENDING: "ORDER_COLLECTIONS_PRICE_ASCENDING",
  ORDER_COLLECTIONS_PRICE_DESCENDING: "ORDER_COLLECTIONS_PRICE_DESCENDING",
  FILTER_COLLECTIONS: "FILTER_COLLECTIONS",
  FILTER_COLORS: "FILTER_COLORS",
  FILTER_SIZES: "FILTER_SIZES",
  FILTER_FIT: "FILTER_FIT",
};

export default collectionsActionTypes;
