const collectionsActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  ORDER_COLLECTIONS_PRICE_ASCENDING: "ORDER_COLLECTIONS_PRICE_ASCENDING",
  ORDER_COLLECTIONS_PRICE_DESCENDING: "ORDER_COLLECTIONS_PRICE_DESCENDING",
  RESET_ORDER_COLLECTIONS: "RESET_ORDER_COLLECTIONS",
  FILTER_COLORS: "FILTER_COLORS",
  FILTER_SIZES: "FILTER_SIZES",
  FILTER_FIT: "FILTER_FIT",
  REDUCE_DISPLAYED_ITEMS: "REDUCE_DISPLAYED_ITEMS",
  ENLARGE_DISPLAYED_ITEMS: "ENLARGE_DISPLAYED_ITEMS",
  SELECT_ITEM: "SELECT_ITEM",
};

export default collectionsActionTypes;
