const shopActionTypes = {
  REQUEST_ITEM_START: "REQUEST_ITEM_START",
  REQUEST_ITEM_SUCCESS: "REQUEST_ITEM_SUCCESS",
  REQUEST_ITEM_FAILURE: "REQUEST_ITEM_FAILURE",
  FETCH_SEARCH_START:"FETCH_SEARCH_START",
  FETCH_SEARCH_SUCCESS:"FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE:"FETCH_SEARCH_FAILURE",
};

export default shopActionTypes;
