const sizesGuideActionTypes = {
  FETCH_SIZES_GUIDE_START: "FETCH_SIZES_GUIDE_START",
  FETCH_SIZES_GUIDE_SUCCESS: "FETCH_SIZES_GUIDE_SUCCESS",
  FETCH_SIZES_GUIDE_FAILURE: "FETCH_SIZES_GUIDE_FAILURE",
};

export default sizesGuideActionTypes;
