const wishlistActionTypes = {
  TOGGLE_ITEM: "TOGGLE_ITEM",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SELECT_SIZE: "SELECT_SIZE",
  CLEAR_SIZE: "CLEAR_SIZE",
  CLEAR_WISHLIST: "CLEAR_WISHLIST",
  UPDATE_WISHLIST_SUCCESS: "UPDATE_WISHLIST_SUCCESS",
  UPDATE_WISHLIST_FAILURE: "UPDATE_WISHLIST_FAILURE",
  // CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};

export default wishlistActionTypes;
