const wishlistActionTypes = {
  TOGGLE_WISHLIST_ITEM: "TOGGLE_WISHLIST_ITEM",
  ADD_ITEM_TO_WISHLIST: "ADD_ITEM_TO_WISHLIST",
  REMOVE_ITEM_FROM_WISHLIST: "REMOVE_ITEM_FROM_WISHLIST",
  SELECT_SIZE: "SELECT_SIZE",
  CLEAR_SIZE: "CLEAR_SIZE",
  CLEAR_WISHLIST: "CLEAR_WISHLIST",
  UPDATE_WISHLIST_SUCCESS: "UPDATE_WISHLIST_SUCCESS",
  UPDATE_WISHLIST_FAILURE: "UPDATE_WISHLIST_FAILURE",
  ADD_FROM_WISHLIST_TO_CART: "ADD_FROM_WISHLIST_TO_CART",
};

export default wishlistActionTypes;
